//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.OData.OData.Query.Configuration
{
    
    
    /// <summary>
    /// The AggregationConfiguration Configuration Section.
    /// </summary>
    public partial class AggregationConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the AggregationConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AggregationConfigurationSectionName = "aggregation";
        
        /// <summary>
        /// The XML path of the AggregationConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string AggregationConfigurationSectionPath = "aggregation";
        
        /// <summary>
        /// Gets the AggregationConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration Instance
        {
            get
            {
                return ((global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.AggregationConfigurationSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ExternalLibraries Property
        /// <summary>
        /// The XML name of the <see cref="ExternalLibraries"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string ExternalLibrariesPropertyName = "externalLibraries";
        
        /// <summary>
        /// Gets or sets the ExternalLibraries.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The ExternalLibraries.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.ExternalLibrariesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::System.Web.OData.OData.Query.Configuration.ExternalLibraries ExternalLibraries
        {
            get
            {
                return ((global::System.Web.OData.OData.Query.Configuration.ExternalLibraries)(base[global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.ExternalLibrariesPropertyName]));
            }
            set
            {
                base[global::System.Web.OData.OData.Query.Configuration.AggregationConfiguration.ExternalLibrariesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace System.Web.OData.OData.Query.Configuration
{
    
    
    /// <summary>
    /// A collection of Location instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::System.Web.OData.OData.Query.Configuration.Location), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::System.Web.OData.OData.Query.Configuration.ExternalLibraries.LocationPropertyName)]
    public partial class ExternalLibraries : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string LocationPropertyName = "location";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::System.Web.OData.OData.Query.Configuration.ExternalLibraries.LocationPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::System.Web.OData.OData.Query.Configuration.ExternalLibraries.LocationPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::System.Web.OData.OData.Query.Configuration.Location)(element)).Uri;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::System.Web.OData.OData.Query.Configuration.Location();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::System.Web.OData.OData.Query.Configuration.Location this[int index]
        {
            get
            {
                return ((global::System.Web.OData.OData.Query.Configuration.Location)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> with the specified key.
        /// </summary>
        /// <param name="uri">The key of the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::System.Web.OData.OData.Query.Configuration.Location this[object uri]
        {
            get
            {
                return ((global::System.Web.OData.OData.Query.Configuration.Location)(base.BaseGet(uri)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="location">The <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::System.Web.OData.OData.Query.Configuration.Location location)
        {
            base.BaseAdd(location);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="location">The <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::System.Web.OData.OData.Query.Configuration.Location location)
        {
            base.BaseRemove(this.GetElementKey(location));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::System.Web.OData.OData.Query.Configuration.Location GetItemAt(int index)
        {
            return ((global::System.Web.OData.OData.Query.Configuration.Location)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> with the specified key.
        /// </summary>
        /// <param name="uri">The key of the <see cref="global::System.Web.OData.OData.Query.Configuration.Location"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::System.Web.OData.OData.Query.Configuration.Location GetItemByKey(string uri)
        {
            return ((global::System.Web.OData.OData.Query.Configuration.Location)(base.BaseGet(((object)(uri)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace System.Web.OData.OData.Query.Configuration
{
    
    
    /// <summary>
    /// The Location Configuration Element.
    /// </summary>
    public partial class Location : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Uri Property
        /// <summary>
        /// The XML name of the <see cref="Uri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UriPropertyName = "uri";
        
        /// <summary>
        /// Gets or sets the Uri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Uri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::System.Web.OData.OData.Query.Configuration.Location.UriPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Uri
        {
            get
            {
                return ((string)(base[global::System.Web.OData.OData.Query.Configuration.Location.UriPropertyName]));
            }
            set
            {
                base[global::System.Web.OData.OData.Query.Configuration.Location.UriPropertyName] = value;
            }
        }
        #endregion
    }
}
